//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertImgTo_HTML.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConvertImgTo_HTML.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   captions = new Array();
        ///
        /////AsciiArtMovieを実現するクラスを定義
        ///function page_Loaded(){
        ///    function MoviePlayer(frames, rendlingElement){
        ///        var _seekPoint = 0;
        ///        var _divArea = rendlingElement;
        ///        var _frames = frames;
        ///        
        ///        //メソッドを定義
        ///        function _move(point){
        ///            _divArea.innerHTML = _frames[point];
        ///            _seekPoint = point;
        ///        }
        ///        function _start(){
        ///            //for(i = _seekPoint; i &lt; _frames.length; i++){
        ///            if(_seekPoint &lt; _frames [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JScript {
            get {
                return ResourceManager.GetString("JScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   body
        ///{
        ///	background-color:#ffffff;
        ///	white-space:nowrap;
        ///}
        ///div
        ///{
        ///	font-size:10px;
        ///	font-family:ＭＳ ゴシック,monospace;
        ///	
        ///	line-height:0.5em;
        ///	letter-spacing:0em;
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Style_AA {
            get {
                return ResourceManager.GetString("Style_AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   body
        ///{
        ///	background-color:#ffffff;
        ///	white-space:nowrap;
        ///	
        ///	line-height:5px;
        ///	letter-spacing:-0.1em;
        ///	
        ///	margin:0px;
        ///	padding:0px;
        ///}
        ///font
        ///{
        ///	font-size:8px;
        ///	font-family:ＭＳ ゴシック,monospace;
        ///	
        ///	margin:0px;
        ///	padding:0px;
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Style_block {
            get {
                return ResourceManager.GetString("Style_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   body
        ///{
        ///	line-height:4pt;
        ///	letter-spacing:-0.1em;
        ///	
        ///	background-color:#000000;
        ///	white-space:nowrap;
        ///}
        ///font
        ///{
        ///	font-size:4pt;
        ///
        ///	padding:0px;
        ///	margin:0px;
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Style_txt {
            get {
                return ResourceManager.GetString("Style_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;html&quot; indent=&quot;yes&quot; /&gt;
        ///  &lt;xsl:param name=&quot;Mode&quot;  select=&quot;default&quot;/&gt;
        ///  &lt;xsl:param name=&quot;StyleSheetHref&quot;/&gt;
        ///  &lt;xsl:param name=&quot;captionIndex&quot; /&gt;
        ///
        ///  &lt;!--html描画時とJs描画時とで改行コードの有無を分けます。--&gt;
        ///  &lt;xsl:template name=&quot;WriteLR&quot;&gt;
        ///    &lt;xsl:if test=&quot;$Mode!=&apos;Movie&apos;&quot;&gt;
        ///      &lt;xsl:text disable-output [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Xslt {
            get {
                return ResourceManager.GetString("Xslt", resourceCulture);
            }
        }
    }
}
